/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculator.rizghz.dev;

import calculator.rizghz.dev.theme.Scheme;

/**
 *
 * @author enigma
 */
public class Calculator extends javax.swing.JFrame {

    /**
     * Creates new form Calculator
     */
    public Calculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Panel = new javax.swing.JPanel();
        btnNum_1 = new javax.swing.JButton();
        btnNum_2 = new javax.swing.JButton();
        btnNum_3 = new javax.swing.JButton();
        btnNum_4 = new javax.swing.JButton();
        btnNum_5 = new javax.swing.JButton();
        btnNum_6 = new javax.swing.JButton();
        btnNum_7 = new javax.swing.JButton();
        btnNum_8 = new javax.swing.JButton();
        btnNum_9 = new javax.swing.JButton();
        btnNum_0 = new javax.swing.JButton();
        btnNeg = new javax.swing.JButton();
        btnDot = new javax.swing.JButton();
        btnEq = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnSub = new javax.swing.JButton();
        btnMulti = new javax.swing.JButton();
        btnDiv = new javax.swing.JButton();
        btnPer = new javax.swing.JButton();
        btnExp = new javax.swing.JButton();
        btnSqrt = new javax.swing.JButton();
        btnDel = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnClearEntry = new javax.swing.JButton();
        btnPerc = new javax.swing.JButton();
        btnMemSub = new javax.swing.JButton();
        btnMemStore = new javax.swing.JButton();
        btnMem = new javax.swing.JButton();
        btnMemClear = new javax.swing.JButton();
        btnMemRecall = new javax.swing.JButton();
        btnMemAdd = new javax.swing.JButton();
        lblOutput = new javax.swing.JLabel();
        lblExpression = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculator");

        Panel.setBackground(new java.awt.Color(32, 32, 32));
        Panel.setPreferredSize(new java.awt.Dimension(490, 722));

        btnNum_1.setBackground(new java.awt.Color(58, 60, 57));
        btnNum_1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnNum_1.setForeground(java.awt.Color.white);
        btnNum_1.setText("1");
        btnNum_1.setBorder(null);
        btnNum_1.setContentAreaFilled(false);
        btnNum_1.setFocusPainted(false);
        btnNum_1.setOpaque(true);
        btnNum_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNum_1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNum_1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNum_1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnNum_1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnNum_1MouseReleased(evt);
            }
        });
        btnNum_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNum_1ActionPerformed(evt);
            }
        });

        btnNum_2.setBackground(new java.awt.Color(58, 60, 57));
        btnNum_2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnNum_2.setForeground(java.awt.Color.white);
        btnNum_2.setText("2");
        btnNum_2.setBorder(null);
        btnNum_2.setContentAreaFilled(false);
        btnNum_2.setFocusPainted(false);
        btnNum_2.setOpaque(true);
        btnNum_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNum_2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNum_2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNum_2MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnNum_2MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnNum_2MouseReleased(evt);
            }
        });
        btnNum_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNum_2ActionPerformed(evt);
            }
        });

        btnNum_3.setBackground(new java.awt.Color(58, 60, 57));
        btnNum_3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnNum_3.setForeground(java.awt.Color.white);
        btnNum_3.setText("3");
        btnNum_3.setBorder(null);
        btnNum_3.setContentAreaFilled(false);
        btnNum_3.setFocusPainted(false);
        btnNum_3.setOpaque(true);
        btnNum_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNum_3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNum_3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNum_3MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnNum_3MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnNum_3MouseReleased(evt);
            }
        });
        btnNum_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNum_3ActionPerformed(evt);
            }
        });

        btnNum_4.setBackground(new java.awt.Color(58, 60, 57));
        btnNum_4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnNum_4.setForeground(java.awt.Color.white);
        btnNum_4.setText("4");
        btnNum_4.setBorder(null);
        btnNum_4.setContentAreaFilled(false);
        btnNum_4.setFocusPainted(false);
        btnNum_4.setOpaque(true);
        btnNum_4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNum_4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNum_4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNum_4MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnNum_4MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnNum_4MouseReleased(evt);
            }
        });
        btnNum_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNum_4ActionPerformed(evt);
            }
        });

        btnNum_5.setBackground(new java.awt.Color(58, 60, 57));
        btnNum_5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnNum_5.setForeground(java.awt.Color.white);
        btnNum_5.setText("5");
        btnNum_5.setBorder(null);
        btnNum_5.setContentAreaFilled(false);
        btnNum_5.setFocusPainted(false);
        btnNum_5.setOpaque(true);
        btnNum_5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNum_5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNum_5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNum_5MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnNum_5MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnNum_5MouseReleased(evt);
            }
        });
        btnNum_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNum_5ActionPerformed(evt);
            }
        });

        btnNum_6.setBackground(new java.awt.Color(58, 60, 57));
        btnNum_6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnNum_6.setForeground(java.awt.Color.white);
        btnNum_6.setText("6");
        btnNum_6.setBorder(null);
        btnNum_6.setContentAreaFilled(false);
        btnNum_6.setFocusPainted(false);
        btnNum_6.setOpaque(true);
        btnNum_6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNum_6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNum_6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNum_6MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnNum_6MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnNum_6MouseReleased(evt);
            }
        });
        btnNum_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNum_6ActionPerformed(evt);
            }
        });

        btnNum_7.setBackground(new java.awt.Color(58, 60, 57));
        btnNum_7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnNum_7.setForeground(java.awt.Color.white);
        btnNum_7.setText("7");
        btnNum_7.setBorder(null);
        btnNum_7.setContentAreaFilled(false);
        btnNum_7.setFocusPainted(false);
        btnNum_7.setOpaque(true);
        btnNum_7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNum_7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNum_7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNum_7MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnNum_7MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnNum_7MouseReleased(evt);
            }
        });
        btnNum_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNum_7ActionPerformed(evt);
            }
        });

        btnNum_8.setBackground(new java.awt.Color(58, 60, 57));
        btnNum_8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnNum_8.setForeground(java.awt.Color.white);
        btnNum_8.setText("8");
        btnNum_8.setBorder(null);
        btnNum_8.setContentAreaFilled(false);
        btnNum_8.setFocusPainted(false);
        btnNum_8.setOpaque(true);
        btnNum_8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNum_8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNum_8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNum_8MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnNum_8MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnNum_8MouseReleased(evt);
            }
        });
        btnNum_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNum_8ActionPerformed(evt);
            }
        });

        btnNum_9.setBackground(new java.awt.Color(58, 60, 57));
        btnNum_9.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnNum_9.setForeground(java.awt.Color.white);
        btnNum_9.setText("9");
        btnNum_9.setBorder(null);
        btnNum_9.setContentAreaFilled(false);
        btnNum_9.setFocusPainted(false);
        btnNum_9.setOpaque(true);
        btnNum_9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNum_9MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNum_9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNum_9MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnNum_9MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnNum_9MouseReleased(evt);
            }
        });
        btnNum_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNum_9ActionPerformed(evt);
            }
        });

        btnNum_0.setBackground(new java.awt.Color(58, 60, 57));
        btnNum_0.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnNum_0.setForeground(java.awt.Color.white);
        btnNum_0.setText("0");
        btnNum_0.setBorder(null);
        btnNum_0.setContentAreaFilled(false);
        btnNum_0.setFocusPainted(false);
        btnNum_0.setOpaque(true);
        btnNum_0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNum_0MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNum_0MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNum_0MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnNum_0MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnNum_0MouseReleased(evt);
            }
        });
        btnNum_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNum_0ActionPerformed(evt);
            }
        });

        btnNeg.setBackground(new java.awt.Color(58, 60, 57));
        btnNeg.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnNeg.setForeground(java.awt.Color.white);
        btnNeg.setText("- x");
        btnNeg.setBorder(null);
        btnNeg.setContentAreaFilled(false);
        btnNeg.setFocusPainted(false);
        btnNeg.setOpaque(true);
        btnNeg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNegMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNegMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNegMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnNegMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnNegMouseReleased(evt);
            }
        });

        btnDot.setBackground(new java.awt.Color(58, 60, 57));
        btnDot.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnDot.setForeground(java.awt.Color.white);
        btnDot.setText(".");
        btnDot.setBorder(null);
        btnDot.setContentAreaFilled(false);
        btnDot.setFocusPainted(false);
        btnDot.setOpaque(true);
        btnDot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDotMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDotMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDotMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnDotMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnDotMouseReleased(evt);
            }
        });

        btnEq.setBackground(new java.awt.Color(64, 78, 113));
        btnEq.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnEq.setForeground(new java.awt.Color(32, 32, 31));
        btnEq.setText("=");
        btnEq.setBorder(null);
        btnEq.setContentAreaFilled(false);
        btnEq.setFocusPainted(false);
        btnEq.setOpaque(true);
        btnEq.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEqMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEqMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEqMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnEqMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnEqMouseReleased(evt);
            }
        });

        btnAdd.setBackground(new java.awt.Color(49, 51, 49));
        btnAdd.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnAdd.setForeground(java.awt.Color.white);
        btnAdd.setText("+");
        btnAdd.setBorder(null);
        btnAdd.setContentAreaFilled(false);
        btnAdd.setFocusPainted(false);
        btnAdd.setOpaque(true);
        btnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAddMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAddMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnAddMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnAddMouseReleased(evt);
            }
        });

        btnSub.setBackground(new java.awt.Color(49, 51, 49));
        btnSub.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnSub.setForeground(java.awt.Color.white);
        btnSub.setText("-");
        btnSub.setBorder(null);
        btnSub.setContentAreaFilled(false);
        btnSub.setFocusPainted(false);
        btnSub.setOpaque(true);
        btnSub.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSubMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSubMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSubMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSubMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnSubMouseReleased(evt);
            }
        });

        btnMulti.setBackground(new java.awt.Color(49, 51, 49));
        btnMulti.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnMulti.setForeground(java.awt.Color.white);
        btnMulti.setText("×");
        btnMulti.setBorder(null);
        btnMulti.setContentAreaFilled(false);
        btnMulti.setFocusPainted(false);
        btnMulti.setOpaque(true);
        btnMulti.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMultiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMultiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMultiMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnMultiMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnMultiMouseReleased(evt);
            }
        });

        btnDiv.setBackground(new java.awt.Color(49, 51, 49));
        btnDiv.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnDiv.setForeground(java.awt.Color.white);
        btnDiv.setText("÷");
        btnDiv.setBorder(null);
        btnDiv.setContentAreaFilled(false);
        btnDiv.setFocusPainted(false);
        btnDiv.setOpaque(true);
        btnDiv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDivMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDivMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDivMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnDivMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnDivMouseReleased(evt);
            }
        });

        btnPer.setBackground(new java.awt.Color(49, 51, 49));
        btnPer.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnPer.setForeground(java.awt.Color.white);
        btnPer.setText("¹/x");
        btnPer.setBorder(null);
        btnPer.setContentAreaFilled(false);
        btnPer.setFocusPainted(false);
        btnPer.setOpaque(true);
        btnPer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPerMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnPerMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnPerMouseReleased(evt);
            }
        });

        btnExp.setBackground(new java.awt.Color(49, 51, 49));
        btnExp.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnExp.setForeground(java.awt.Color.white);
        btnExp.setText("x²");
        btnExp.setBorder(null);
        btnExp.setContentAreaFilled(false);
        btnExp.setFocusPainted(false);
        btnExp.setOpaque(true);
        btnExp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExpMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExpMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnExpMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnExpMouseReleased(evt);
            }
        });

        btnSqrt.setBackground(new java.awt.Color(49, 51, 49));
        btnSqrt.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnSqrt.setForeground(java.awt.Color.white);
        btnSqrt.setText("√x");
        btnSqrt.setBorder(null);
        btnSqrt.setContentAreaFilled(false);
        btnSqrt.setFocusPainted(false);
        btnSqrt.setOpaque(true);
        btnSqrt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSqrtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSqrtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSqrtMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSqrtMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnSqrtMouseReleased(evt);
            }
        });

        btnDel.setBackground(new java.awt.Color(49, 51, 49));
        btnDel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnDel.setForeground(java.awt.Color.white);
        btnDel.setText("←");
        btnDel.setBorder(null);
        btnDel.setContentAreaFilled(false);
        btnDel.setFocusPainted(false);
        btnDel.setOpaque(true);
        btnDel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnDelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnDelMouseReleased(evt);
            }
        });

        btnClear.setBackground(new java.awt.Color(49, 51, 49));
        btnClear.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnClear.setForeground(java.awt.Color.white);
        btnClear.setText("C");
        btnClear.setBorder(null);
        btnClear.setContentAreaFilled(false);
        btnClear.setFocusPainted(false);
        btnClear.setOpaque(true);
        btnClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClearMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnClearMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnClearMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnClearMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnClearMouseReleased(evt);
            }
        });

        btnClearEntry.setBackground(new java.awt.Color(49, 51, 49));
        btnClearEntry.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnClearEntry.setForeground(java.awt.Color.white);
        btnClearEntry.setText("CE");
        btnClearEntry.setBorder(null);
        btnClearEntry.setContentAreaFilled(false);
        btnClearEntry.setFocusPainted(false);
        btnClearEntry.setOpaque(true);
        btnClearEntry.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClearEntryMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnClearEntryMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnClearEntryMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnClearEntryMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnClearEntryMouseReleased(evt);
            }
        });

        btnPerc.setBackground(new java.awt.Color(49, 51, 49));
        btnPerc.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnPerc.setForeground(java.awt.Color.white);
        btnPerc.setText("%");
        btnPerc.setBorder(null);
        btnPerc.setContentAreaFilled(false);
        btnPerc.setFocusPainted(false);
        btnPerc.setOpaque(true);
        btnPerc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPercMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPercMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPercMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnPercMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnPercMouseReleased(evt);
            }
        });

        btnMemSub.setBackground(new java.awt.Color(32, 32, 32));
        btnMemSub.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnMemSub.setForeground(new java.awt.Color(102, 102, 102));
        btnMemSub.setText("M-");
        btnMemSub.setBorder(null);
        btnMemSub.setContentAreaFilled(false);
        btnMemSub.setFocusPainted(false);
        btnMemSub.setOpaque(true);

        btnMemStore.setBackground(new java.awt.Color(32, 32, 32));
        btnMemStore.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnMemStore.setForeground(new java.awt.Color(102, 102, 102));
        btnMemStore.setText("MS");
        btnMemStore.setBorder(null);
        btnMemStore.setContentAreaFilled(false);
        btnMemStore.setFocusPainted(false);
        btnMemStore.setOpaque(true);

        btnMem.setBackground(new java.awt.Color(32, 32, 32));
        btnMem.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnMem.setForeground(new java.awt.Color(102, 102, 102));
        btnMem.setText("M");
        btnMem.setBorder(null);
        btnMem.setContentAreaFilled(false);
        btnMem.setFocusPainted(false);
        btnMem.setOpaque(true);

        btnMemClear.setBackground(new java.awt.Color(32, 32, 32));
        btnMemClear.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnMemClear.setForeground(new java.awt.Color(102, 102, 102));
        btnMemClear.setText("MC");
        btnMemClear.setBorder(null);
        btnMemClear.setContentAreaFilled(false);
        btnMemClear.setFocusPainted(false);
        btnMemClear.setOpaque(true);

        btnMemRecall.setBackground(new java.awt.Color(32, 32, 32));
        btnMemRecall.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnMemRecall.setForeground(new java.awt.Color(102, 102, 102));
        btnMemRecall.setText("MR");
        btnMemRecall.setBorder(null);
        btnMemRecall.setContentAreaFilled(false);
        btnMemRecall.setFocusPainted(false);
        btnMemRecall.setOpaque(true);

        btnMemAdd.setBackground(new java.awt.Color(32, 32, 32));
        btnMemAdd.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnMemAdd.setForeground(new java.awt.Color(102, 102, 102));
        btnMemAdd.setText("M+");
        btnMemAdd.setBorder(null);
        btnMemAdd.setContentAreaFilled(false);
        btnMemAdd.setFocusPainted(false);
        btnMemAdd.setOpaque(true);

        lblOutput.setFont(new java.awt.Font("Arial Narrow", 1, 48)); // NOI18N
        lblOutput.setForeground(java.awt.Color.white);
        lblOutput.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblOutput.setText("0");
        lblOutput.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        lblExpression.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblExpression.setForeground(new java.awt.Color(102, 102, 102));
        lblExpression.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblExpression.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculator/rizghz/dev/Icon.png"))); // NOI18N
        jLabel2.setText(" Standard");

        javax.swing.GroupLayout PanelLayout = new javax.swing.GroupLayout(Panel);
        Panel.setLayout(PanelLayout);
        PanelLayout.setHorizontalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelLayout.createSequentialGroup()
                                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelLayout.createSequentialGroup()
                                        .addComponent(btnMemClear, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnMemRecall, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnMemAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(PanelLayout.createSequentialGroup()
                                        .addComponent(btnPerc, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnClearEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelLayout.createSequentialGroup()
                                        .addComponent(btnMemSub, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnMemStore, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnMem, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(PanelLayout.createSequentialGroup()
                                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnDel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(PanelLayout.createSequentialGroup()
                                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelLayout.createSequentialGroup()
                                        .addComponent(btnNeg, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnNum_0, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnDot, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnEq, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(PanelLayout.createSequentialGroup()
                                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnNum_7, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnPer, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(PanelLayout.createSequentialGroup()
                                                .addComponent(btnNum_8, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnNum_9, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnMulti, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(PanelLayout.createSequentialGroup()
                                                .addComponent(btnExp, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnSqrt, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(PanelLayout.createSequentialGroup()
                                        .addComponent(btnNum_4, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnNum_5, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnNum_6, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnSub, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(PanelLayout.createSequentialGroup()
                                        .addComponent(btnNum_1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnNum_2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnNum_3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblOutput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblExpression, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PanelLayout.setVerticalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblExpression, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMemAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMemClear, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMemRecall, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMemSub, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMemStore, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMem, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnClearEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnDel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnPerc, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExp, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPer, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSqrt, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNum_7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNum_8, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNum_9, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMulti, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNum_4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNum_5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNum_6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSub, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNum_2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNum_1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNum_3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNum_0, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNeg, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDot, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEq, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(Panel, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNum_1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNum_1MouseEntered
        btnNum_1.setBackground(Scheme.grey_2);
    }//GEN-LAST:event_btnNum_1MouseEntered

    private void btnNum_1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNum_1MouseExited
        btnNum_1.setBackground(Scheme.grey_1);
    }//GEN-LAST:event_btnNum_1MouseExited

    private void btnNum_1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNum_1MousePressed
        btnNum_1.setBackground(Scheme.grey_3);
    }//GEN-LAST:event_btnNum_1MousePressed

    private void btnNum_2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNum_2MouseEntered
        btnNum_2.setBackground(Scheme.grey_2);
    }//GEN-LAST:event_btnNum_2MouseEntered

    private void btnNum_2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNum_2MouseExited
        btnNum_2.setBackground(Scheme.grey_1);
    }//GEN-LAST:event_btnNum_2MouseExited

    private void btnNum_2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNum_2MousePressed
        btnNum_2.setBackground(Scheme.grey_3);
    }//GEN-LAST:event_btnNum_2MousePressed

    private void btnNum_3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNum_3MouseEntered
        btnNum_3.setBackground(Scheme.grey_2);
    }//GEN-LAST:event_btnNum_3MouseEntered

    private void btnNum_3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNum_3MouseExited
        btnNum_3.setBackground(Scheme.grey_1);
    }//GEN-LAST:event_btnNum_3MouseExited

    private void btnNum_3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNum_3MousePressed
        btnNum_3.setBackground(Scheme.grey_3);
    }//GEN-LAST:event_btnNum_3MousePressed

    private void btnNum_4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNum_4MouseEntered
        btnNum_4.setBackground(Scheme.grey_2);
    }//GEN-LAST:event_btnNum_4MouseEntered

    private void btnNum_4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNum_4MouseExited
        btnNum_4.setBackground(Scheme.grey_1);
    }//GEN-LAST:event_btnNum_4MouseExited

    private void btnNum_4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNum_4MousePressed
        btnNum_4.setBackground(Scheme.grey_3);
    }//GEN-LAST:event_btnNum_4MousePressed

    private void btnNum_5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNum_5MouseEntered
        btnNum_5.setBackground(Scheme.grey_2);
    }//GEN-LAST:event_btnNum_5MouseEntered

    private void btnNum_5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNum_5MouseExited
        btnNum_5.setBackground(Scheme.grey_1);
    }//GEN-LAST:event_btnNum_5MouseExited

    private void btnNum_5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNum_5MousePressed
        btnNum_5.setBackground(Scheme.grey_3);
    }//GEN-LAST:event_btnNum_5MousePressed

    private void btnNum_6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNum_6MouseEntered
        btnNum_6.setBackground(Scheme.grey_2);
    }//GEN-LAST:event_btnNum_6MouseEntered

    private void btnNum_6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNum_6MouseExited
        btnNum_6.setBackground(Scheme.grey_1);
    }//GEN-LAST:event_btnNum_6MouseExited

    private void btnNum_6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNum_6MousePressed
        btnNum_6.setBackground(Scheme.grey_3);
    }//GEN-LAST:event_btnNum_6MousePressed

    private void btnNum_7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNum_7MouseEntered
        btnNum_7.setBackground(Scheme.grey_2);
    }//GEN-LAST:event_btnNum_7MouseEntered

    private void btnNum_7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNum_7MouseExited
        btnNum_7.setBackground(Scheme.grey_1);
    }//GEN-LAST:event_btnNum_7MouseExited

    private void btnNum_7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNum_7MousePressed
        btnNum_7.setBackground(Scheme.grey_3);
    }//GEN-LAST:event_btnNum_7MousePressed

    private void btnNum_8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNum_8MouseEntered
        btnNum_8.setBackground(Scheme.grey_2);
    }//GEN-LAST:event_btnNum_8MouseEntered

    private void btnNum_8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNum_8MouseExited
        btnNum_8.setBackground(Scheme.grey_1);
    }//GEN-LAST:event_btnNum_8MouseExited

    private void btnNum_8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNum_8MousePressed
        btnNum_8.setBackground(Scheme.grey_3);
    }//GEN-LAST:event_btnNum_8MousePressed

    private void btnNum_9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNum_9MouseEntered
        btnNum_9.setBackground(Scheme.grey_2);
    }//GEN-LAST:event_btnNum_9MouseEntered

    private void btnNum_9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNum_9MouseExited
        btnNum_9.setBackground(Scheme.grey_1);
    }//GEN-LAST:event_btnNum_9MouseExited

    private void btnNum_9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNum_9MousePressed
        btnNum_9.setBackground(Scheme.grey_3);
    }//GEN-LAST:event_btnNum_9MousePressed

    private void btnNegMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNegMouseEntered
        btnNeg.setBackground(Scheme.grey_2);
    }//GEN-LAST:event_btnNegMouseEntered

    private void btnNegMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNegMouseExited
        btnNeg.setBackground(Scheme.grey_1);
    }//GEN-LAST:event_btnNegMouseExited

    private void btnNegMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNegMousePressed
        btnNeg.setBackground(Scheme.grey_3);
    }//GEN-LAST:event_btnNegMousePressed

    private void btnNum_0MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNum_0MouseEntered
        btnNum_0.setBackground(Scheme.grey_2);
    }//GEN-LAST:event_btnNum_0MouseEntered

    private void btnNum_0MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNum_0MouseExited
        btnNum_0.setBackground(Scheme.grey_1);
    }//GEN-LAST:event_btnNum_0MouseExited

    private void btnNum_0MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNum_0MousePressed
        btnNum_0.setBackground(Scheme.grey_3);
    }//GEN-LAST:event_btnNum_0MousePressed

    private void btnDotMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDotMouseEntered
        btnDot.setBackground(Scheme.grey_2);
    }//GEN-LAST:event_btnDotMouseEntered

    private void btnDotMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDotMouseExited
        btnDot.setBackground(Scheme.grey_1);
    }//GEN-LAST:event_btnDotMouseExited

    private void btnDotMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDotMousePressed
        btnDot.setBackground(Scheme.grey_3);
    }//GEN-LAST:event_btnDotMousePressed

    private void btnEqMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEqMouseEntered
        btnEq.setBackground(Scheme.blue_2);
        btnEq.setForeground(Scheme.bg_1);
    }//GEN-LAST:event_btnEqMouseEntered

    private void btnEqMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEqMouseExited
        btnEq.setBackground(Scheme.blue_1);
        btnEq.setForeground(Scheme.bg_1);
    }//GEN-LAST:event_btnEqMouseExited

    private void btnEqMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEqMousePressed
        btnEq.setBackground(Scheme.blue_3);
        btnEq.setForeground(Scheme.grey_3);
    }//GEN-LAST:event_btnEqMousePressed

    private void btnAddMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseEntered
        btnAdd.setBackground(Scheme.grey_1);
    }//GEN-LAST:event_btnAddMouseEntered

    private void btnAddMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseExited
        btnAdd.setBackground(Scheme.grey_2);
    }//GEN-LAST:event_btnAddMouseExited

    private void btnAddMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMousePressed
        btnAdd.setBackground(Scheme.grey_2);
    }//GEN-LAST:event_btnAddMousePressed

    private void btnSubMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubMouseEntered
        btnSub.setBackground(Scheme.grey_1);
    }//GEN-LAST:event_btnSubMouseEntered

    private void btnSubMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubMouseExited
        btnSub.setBackground(Scheme.grey_2);
    }//GEN-LAST:event_btnSubMouseExited

    private void btnSubMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubMousePressed
        btnSub.setBackground(Scheme.grey_2);
    }//GEN-LAST:event_btnSubMousePressed

    private void btnMultiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMultiMouseEntered
        btnMulti.setBackground(Scheme.grey_1);
    }//GEN-LAST:event_btnMultiMouseEntered

    private void btnMultiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMultiMouseExited
        btnMulti.setBackground(Scheme.grey_2);
    }//GEN-LAST:event_btnMultiMouseExited

    private void btnMultiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMultiMousePressed
        btnMulti.setBackground(Scheme.grey_2);
    }//GEN-LAST:event_btnMultiMousePressed

    private void btnDivMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDivMouseEntered
        btnDiv.setBackground(Scheme.grey_1);
    }//GEN-LAST:event_btnDivMouseEntered

    private void btnDivMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDivMouseExited
        btnDiv.setBackground(Scheme.grey_2);
    }//GEN-LAST:event_btnDivMouseExited

    private void btnDivMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDivMousePressed
        btnDiv.setBackground(Scheme.grey_2);
    }//GEN-LAST:event_btnDivMousePressed

    private void btnPerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPerMouseEntered
        btnPer.setBackground(Scheme.grey_1);
    }//GEN-LAST:event_btnPerMouseEntered

    private void btnPerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPerMouseExited
        btnPer.setBackground(Scheme.grey_2);
    }//GEN-LAST:event_btnPerMouseExited

    private void btnPerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPerMousePressed
        btnPer.setBackground(Scheme.grey_2);
    }//GEN-LAST:event_btnPerMousePressed

    private void btnExpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExpMouseEntered
        btnExp.setBackground(Scheme.grey_1);
    }//GEN-LAST:event_btnExpMouseEntered

    private void btnExpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExpMouseExited
        btnExp.setBackground(Scheme.grey_2);
    }//GEN-LAST:event_btnExpMouseExited

    private void btnExpMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExpMousePressed
        btnExp.setBackground(Scheme.grey_2);
    }//GEN-LAST:event_btnExpMousePressed

    private void btnSqrtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSqrtMouseEntered
        btnSqrt.setBackground(Scheme.grey_1);
    }//GEN-LAST:event_btnSqrtMouseEntered

    private void btnSqrtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSqrtMouseExited
        btnSqrt.setBackground(Scheme.grey_2);
    }//GEN-LAST:event_btnSqrtMouseExited

    private void btnSqrtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSqrtMousePressed
        btnSqrt.setBackground(Scheme.grey_2);
    }//GEN-LAST:event_btnSqrtMousePressed

    private void btnDelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDelMouseEntered
        btnDel.setBackground(Scheme.grey_1);
    }//GEN-LAST:event_btnDelMouseEntered

    private void btnDelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDelMouseExited
        btnDel.setBackground(Scheme.grey_2);
    }//GEN-LAST:event_btnDelMouseExited

    private void btnDelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDelMousePressed
        btnDel.setBackground(Scheme.grey_2);
    }//GEN-LAST:event_btnDelMousePressed

    private void btnClearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMouseEntered
        btnClear.setBackground(Scheme.grey_1);
    }//GEN-LAST:event_btnClearMouseEntered

    private void btnClearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMouseExited
        btnClear.setBackground(Scheme.grey_2);
    }//GEN-LAST:event_btnClearMouseExited

    private void btnClearMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMousePressed
        btnClear.setBackground(Scheme.grey_2);
    }//GEN-LAST:event_btnClearMousePressed

    private void btnClearEntryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearEntryMouseEntered
        btnClearEntry.setBackground(Scheme.grey_1);
    }//GEN-LAST:event_btnClearEntryMouseEntered

    private void btnClearEntryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearEntryMouseExited
        btnClearEntry.setBackground(Scheme.grey_2);
    }//GEN-LAST:event_btnClearEntryMouseExited

    private void btnClearEntryMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearEntryMousePressed
        btnClearEntry.setBackground(Scheme.grey_2);
    }//GEN-LAST:event_btnClearEntryMousePressed

    private void btnPercMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPercMouseEntered
        btnPerc.setBackground(Scheme.grey_1);
    }//GEN-LAST:event_btnPercMouseEntered

    private void btnPercMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPercMouseExited
        btnPerc.setBackground(Scheme.grey_2);
    }//GEN-LAST:event_btnPercMouseExited

    private void btnPercMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPercMousePressed
        btnPerc.setBackground(Scheme.grey_2);
    }//GEN-LAST:event_btnPercMousePressed

    private void btnNum_0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNum_0MouseClicked
        btnNum_0.setBackground(Scheme.grey_2);
    }//GEN-LAST:event_btnNum_0MouseClicked

    private void btnNum_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNum_1MouseClicked
        btnNum_1.setBackground(Scheme.grey_2);
    }//GEN-LAST:event_btnNum_1MouseClicked

    private void btnNum_2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNum_2MouseClicked
        btnNum_2.setBackground(Scheme.grey_2);
    }//GEN-LAST:event_btnNum_2MouseClicked

    private void btnNum_3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNum_3MouseClicked
        btnNum_3.setBackground(Scheme.grey_2);
    }//GEN-LAST:event_btnNum_3MouseClicked

    private void btnNum_4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNum_4MouseClicked
        btnNum_4.setBackground(Scheme.grey_2);
    }//GEN-LAST:event_btnNum_4MouseClicked

    private void btnNum_5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNum_5MouseClicked
        btnNum_5.setBackground(Scheme.grey_2);
    }//GEN-LAST:event_btnNum_5MouseClicked

    private void btnNum_6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNum_6MouseClicked
        btnNum_6.setBackground(Scheme.grey_2);
    }//GEN-LAST:event_btnNum_6MouseClicked

    private void btnNum_7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNum_7MouseClicked
        btnNum_7.setBackground(Scheme.grey_2);
    }//GEN-LAST:event_btnNum_7MouseClicked

    private void btnNum_8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNum_8MouseClicked
        btnNum_8.setBackground(Scheme.grey_2);
    }//GEN-LAST:event_btnNum_8MouseClicked

    private void btnNum_9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNum_9MouseClicked
        btnNum_9.setBackground(Scheme.grey_2);
    }//GEN-LAST:event_btnNum_9MouseClicked

    private void btnNegMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNegMouseClicked
        btnNeg.setBackground(Scheme.grey_2);
    }//GEN-LAST:event_btnNegMouseClicked

    private void btnDotMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDotMouseClicked
        btnDot.setBackground(Scheme.grey_2);
    }//GEN-LAST:event_btnDotMouseClicked

    private void btnNum_1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNum_1MouseReleased
        btnNum_1.setBackground(Scheme.grey_2);
    }//GEN-LAST:event_btnNum_1MouseReleased

    private void btnNum_2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNum_2MouseReleased
        btnNum_2.setBackground(Scheme.grey_2);
    }//GEN-LAST:event_btnNum_2MouseReleased

    private void btnNum_3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNum_3MouseReleased
        btnNum_3.setBackground(Scheme.grey_2);
    }//GEN-LAST:event_btnNum_3MouseReleased

    private void btnNum_4MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNum_4MouseReleased
        btnNum_4.setBackground(Scheme.grey_2);
    }//GEN-LAST:event_btnNum_4MouseReleased

    private void btnNum_5MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNum_5MouseReleased
        btnNum_5.setBackground(Scheme.grey_2);
    }//GEN-LAST:event_btnNum_5MouseReleased

    private void btnNum_6MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNum_6MouseReleased
        btnNum_6.setBackground(Scheme.grey_2);
    }//GEN-LAST:event_btnNum_6MouseReleased

    private void btnNum_7MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNum_7MouseReleased
        btnNum_7.setBackground(Scheme.grey_2);
    }//GEN-LAST:event_btnNum_7MouseReleased

    private void btnNum_8MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNum_8MouseReleased
        btnNum_8.setBackground(Scheme.grey_2);
    }//GEN-LAST:event_btnNum_8MouseReleased

    private void btnNum_9MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNum_9MouseReleased
        btnNum_9.setBackground(Scheme.grey_2);
    }//GEN-LAST:event_btnNum_9MouseReleased

    private void btnNum_0MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNum_0MouseReleased
        btnNum_0.setBackground(Scheme.grey_2);
    }//GEN-LAST:event_btnNum_0MouseReleased

    private void btnNegMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNegMouseReleased
        btnNeg.setBackground(Scheme.grey_2);
    }//GEN-LAST:event_btnNegMouseReleased

    private void btnDotMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDotMouseReleased
        btnDot.setBackground(Scheme.grey_2);
    }//GEN-LAST:event_btnDotMouseReleased

    private void btnEqMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEqMouseClicked
        btnEq.setBackground(Scheme.blue_2);
        btnEq.setForeground(Scheme.bg_1);
    }//GEN-LAST:event_btnEqMouseClicked

    private void btnEqMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEqMouseReleased
        btnEq.setBackground(Scheme.blue_2);
        btnEq.setForeground(Scheme.bg_1);
    }//GEN-LAST:event_btnEqMouseReleased

    private void btnAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseClicked
        btnAdd.setBackground(Scheme.grey_1);
    }//GEN-LAST:event_btnAddMouseClicked

    private void btnAddMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseReleased
        btnAdd.setBackground(Scheme.grey_1);
    }//GEN-LAST:event_btnAddMouseReleased

    private void btnSubMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubMouseClicked
        btnSub.setBackground(Scheme.grey_1);
    }//GEN-LAST:event_btnSubMouseClicked

    private void btnSubMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubMouseReleased
        btnSub.setBackground(Scheme.grey_1);
    }//GEN-LAST:event_btnSubMouseReleased

    private void btnMultiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMultiMouseClicked
        btnMulti.setBackground(Scheme.grey_1);
    }//GEN-LAST:event_btnMultiMouseClicked

    private void btnMultiMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMultiMouseReleased
        btnMulti.setBackground(Scheme.grey_1);
    }//GEN-LAST:event_btnMultiMouseReleased

    private void btnDivMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDivMouseClicked
        btnDiv.setBackground(Scheme.grey_1);
    }//GEN-LAST:event_btnDivMouseClicked

    private void btnDivMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDivMouseReleased
        btnDiv.setBackground(Scheme.grey_1);
    }//GEN-LAST:event_btnDivMouseReleased

    private void btnSqrtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSqrtMouseClicked
        btnSqrt.setBackground(Scheme.grey_1);
    }//GEN-LAST:event_btnSqrtMouseClicked

    private void btnSqrtMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSqrtMouseReleased
        btnSqrt.setBackground(Scheme.grey_1);
    }//GEN-LAST:event_btnSqrtMouseReleased

    private void btnExpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExpMouseClicked
        btnExp.setBackground(Scheme.grey_1);
    }//GEN-LAST:event_btnExpMouseClicked

    private void btnExpMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExpMouseReleased
        btnExp.setBackground(Scheme.grey_1);
    }//GEN-LAST:event_btnExpMouseReleased

    private void btnPerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPerMouseClicked
        btnPer.setBackground(Scheme.grey_1);
    }//GEN-LAST:event_btnPerMouseClicked

    private void btnPerMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPerMouseReleased
        btnPer.setBackground(Scheme.grey_1);
    }//GEN-LAST:event_btnPerMouseReleased

    private void btnPercMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPercMouseClicked
        btnPerc.setBackground(Scheme.grey_1);
    }//GEN-LAST:event_btnPercMouseClicked

    private void btnPercMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPercMouseReleased
        btnPerc.setBackground(Scheme.grey_1);
    }//GEN-LAST:event_btnPercMouseReleased

    private void btnClearEntryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearEntryMouseClicked
        btnClearEntry.setBackground(Scheme.grey_1);
    }//GEN-LAST:event_btnClearEntryMouseClicked

    private void btnClearEntryMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearEntryMouseReleased
        btnClearEntry.setBackground(Scheme.grey_1);
    }//GEN-LAST:event_btnClearEntryMouseReleased

    private void btnClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMouseClicked
        btnClear.setBackground(Scheme.grey_1);
    }//GEN-LAST:event_btnClearMouseClicked

    private void btnClearMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMouseReleased
        btnClear.setBackground(Scheme.grey_1);
    }//GEN-LAST:event_btnClearMouseReleased

    private void btnDelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDelMouseClicked
        btnDel.setBackground(Scheme.grey_1);
    }//GEN-LAST:event_btnDelMouseClicked

    private void btnDelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDelMouseReleased
        btnDel.setBackground(Scheme.grey_1);
    }//GEN-LAST:event_btnDelMouseReleased

    private void btnNum_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNum_0ActionPerformed
        if (!lblOutput.getText().equals("0")) {
            lblOutput.setText(lblOutput.getText() + "0");
        }
    }//GEN-LAST:event_btnNum_0ActionPerformed

    private void btnNum_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNum_1ActionPerformed
        if (lblOutput.getText().equals("0")) {
            lblOutput.setText("1");
        } else {
            lblOutput.setText(lblOutput.getText() + "1");
        }
    }//GEN-LAST:event_btnNum_1ActionPerformed

    private void btnNum_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNum_2ActionPerformed
        if (lblOutput.getText().equals("0")) {
            lblOutput.setText("2");
        } else {
            lblOutput.setText(lblOutput.getText() + "2");
        }
    }//GEN-LAST:event_btnNum_2ActionPerformed

    private void btnNum_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNum_3ActionPerformed
        if (lblOutput.getText().equals("0")) {
            lblOutput.setText("3");
        } else {
            lblOutput.setText(lblOutput.getText() + "3");
        }
    }//GEN-LAST:event_btnNum_3ActionPerformed

    private void btnNum_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNum_4ActionPerformed
        if (lblOutput.getText().equals("0")) {
            lblOutput.setText("4");
        } else {
            lblOutput.setText(lblOutput.getText() + "4");
        }
    }//GEN-LAST:event_btnNum_4ActionPerformed

    private void btnNum_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNum_5ActionPerformed
        if (lblOutput.getText().equals("0")) {
            lblOutput.setText("5");
        } else {
            lblOutput.setText(lblOutput.getText() + "5");
        }
    }//GEN-LAST:event_btnNum_5ActionPerformed

    private void btnNum_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNum_6ActionPerformed
        if (lblOutput.getText().equals("0")) {
            lblOutput.setText("6");
        } else {
            lblOutput.setText(lblOutput.getText() + "6");
        }
    }//GEN-LAST:event_btnNum_6ActionPerformed

    private void btnNum_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNum_7ActionPerformed
        if (lblOutput.getText().equals("0")) {
            lblOutput.setText("7");
        } else {
            lblOutput.setText(lblOutput.getText() + "7");
        }
    }//GEN-LAST:event_btnNum_7ActionPerformed

    private void btnNum_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNum_8ActionPerformed
        if (lblOutput.getText().equals("0")) {
            lblOutput.setText("8");
        } else {
            lblOutput.setText(lblOutput.getText() + "8");
        }
    }//GEN-LAST:event_btnNum_8ActionPerformed

    private void btnNum_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNum_9ActionPerformed
        if (lblOutput.getText().equals("0")) {
            lblOutput.setText("9");
        } else {
            lblOutput.setText(lblOutput.getText() + "9");
        }
    }//GEN-LAST:event_btnNum_9ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }
    
    // reserved
    // size 486x722

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnClearEntry;
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnDiv;
    private javax.swing.JButton btnDot;
    private javax.swing.JButton btnEq;
    private javax.swing.JButton btnExp;
    private javax.swing.JButton btnMem;
    private javax.swing.JButton btnMemAdd;
    private javax.swing.JButton btnMemClear;
    private javax.swing.JButton btnMemRecall;
    private javax.swing.JButton btnMemStore;
    private javax.swing.JButton btnMemSub;
    private javax.swing.JButton btnMulti;
    private javax.swing.JButton btnNeg;
    private javax.swing.JButton btnNum_0;
    private javax.swing.JButton btnNum_1;
    private javax.swing.JButton btnNum_2;
    private javax.swing.JButton btnNum_3;
    private javax.swing.JButton btnNum_4;
    private javax.swing.JButton btnNum_5;
    private javax.swing.JButton btnNum_6;
    private javax.swing.JButton btnNum_7;
    private javax.swing.JButton btnNum_8;
    private javax.swing.JButton btnNum_9;
    private javax.swing.JButton btnPer;
    private javax.swing.JButton btnPerc;
    private javax.swing.JButton btnSqrt;
    private javax.swing.JButton btnSub;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblExpression;
    private javax.swing.JLabel lblOutput;
    // End of variables declaration//GEN-END:variables
}
